export interface QuizQuestion { prompt: string; choices: string[]; answer: number; explanation: string }
export interface Lesson { id: string; week: number; title: string; subtitle: string; concept: string; rules: string[]; example: { label: string; text: string }; mission: string; questions: QuizQuestion[] }
export const CHAPTERS = [
  { title: "Find the story in the numbers", subtitle: "Averages, outliers & everyday comparisons" },
  { title: "Get comfortable with uncertainty", subtitle: "Probability, independence & expected value" },
  { title: "Make sense of your money", subtitle: "Growth, risk & weighted averages" },
  { title: "Be a better numbers detective", subtitle: "Samples, claims & real-world decisions" },
];
const q = (prompt: string, choices: string[], answer: number, explanation: string): QuizQuestion => ({ prompt, choices, answer, explanation });
export const LESSONS: Lesson[] = [
  {
    id: "mean", week: 1, title: "What does “average” really mean?", subtitle: "Find your typical daily spending", concept: "The mean shares a total equally across all observations. It is a useful starting point for budgets, habits, and comparisons.",
    rules: ["Add all the values, then divide by how many there are.", "Include zero days when they belong in the period you are measuring.", "A mean describes the group; individual days can look very different."],
    example: {label: "THE COFFEE EXAMPLE", text: "You spend $4, $6, and $5 over three days. Your mean is ($4 + $6 + $5) ÷ 3 = $5 per day."}, mission: "Write down your spending for three days and calculate your daily mean.",
    questions: [q("You spend $8, $10, $12, and $14 on lunch. What is the mean?",["$10","$11","$12","$44"],1,"The total is $44. Divide by 4 lunches to get $11."),q("Your coffee spending is $6, $0, and $3. What is the daily mean?",["$4.50","$9","$3","$6"],2,"The zero-spend day still counts: ($6 + $0 + $3) ÷ 3 = $3."),q("You average 20 minutes of walking per day for 5 days. How many minutes in total?",["25","50","100","4"],2,"Mean × number of days = total: 20 × 5 = 100 minutes.")],
  },
  {
    id: "median", week: 1, title: "When the middle tells a better story", subtitle: "Keep outliers from fooling you", concept: "The median is the middle value after sorting. Extreme values can pull the mean around, while the median often better describes a typical rent, salary, or delivery time.",
    rules: ["Sort values from smallest to largest and take the middle.","For an even number of values, average the two middle ones.","An outlier is unusual, but is not automatically a mistake."],
    example: {label: "THE DELIVERY EXAMPLE",text: "Deliveries take 10, 12, 13, 15, and 100 minutes. The median is 13 minutes, while the mean is 30 minutes."},mission:"Find a housing or salary article. Does it report the mean or median, and why might that matter?",
    questions:[q("Your lunch bills are $12, $14, $15, $16, and $85. What is the median?",["$15","$28.40","$16","$14"],0,"The ordered middle value is $15. The $85 bill pulls the mean up to $28.40."),q("What is the median of 4, 8, 10, and 18?",["8","10","9","11"],2,"With four values, average the middle two: (8 + 10) ÷ 2 = 9."),q("One billionaire joins a small company. Which salary measure is usually pulled upward most?",["Median","Mean","Minimum","Number of employees' previous salaries"],1,"The mean uses every dollar, so one enormous salary can change it dramatically.")],
  },
  {
    id:"spread",week:1,title:"The average is only half the story",subtitle:"Spot consistency and variation",concept:"Two groups can have the same mean and very different variation. Spread helps you think about reliability, waiting times, and how predictable an outcome is.",rules:["Range = largest value − smallest value.","Standard deviation describes how far values tend to sit from their mean.","Use center and spread together; a single average hides variation."],example:{label:"THE COMMUTE EXAMPLE",text:"Route A takes 19, 20, 21 minutes. Route B takes 5, 20, 35. Both average 20 minutes, but A is more consistent."},mission:"Record five commute or delivery times. Find the mean and range.",questions:[q("A delivery takes 12, 15, 18, and 25 minutes across four orders. What is the range?",["37 minutes","13 minutes","18 minutes","4 minutes"],1,"Largest minus smallest: 25 − 12 = 13 minutes."),q("A takes 19, 20, 21 minutes; B takes 5, 20, 35. Which is more predictable from these observations?",["Route B","Neither has an average","Route A","They are equally consistent"],2,"Both means are 20, but A has much less spread."),q("Two datasets have the same units and mean. A higher standard deviation indicates…",["More spread around the mean","A larger sample size","A guaranteed higher next value","No outliers"],0,"Standard deviation measures spread, not sample size or a guarantee about future observations.")],
  },
  {
    id:"probability",week:2,title:"Turn “maybe” into a number",subtitle:"Reason about everyday chances",concept:"Probability describes how likely an event is, from 0% (impossible) to 100% (certain). For equally likely outcomes, count the outcomes you want and divide by all outcomes.",rules:["Probability = favorable outcomes ÷ all equally likely outcomes.","The probability of ‘not A’ is 1 minus the probability of A.","A 70% chance is likely, but it is never a promise."],example:{label:"THE BAG EXAMPLE",text:"A bag contains 3 green tokens and 7 white ones. With each token equally likely, the chance of green is 3 ÷ 10 = 30%."},mission:"Notice one forecast today. Say what its probability does and does not guarantee.",questions:[q("A bag has 3 green tokens and 7 white tokens. What is the chance of drawing green?",["70%","3%","30%","50%"],2,"There are 3 green tokens out of 10 total: 3 ÷ 10 = 30%."),q("A parcel has an 80% chance of arriving today. What is the chance it does not arrive today?",["80%","20%","40%","0%"],1,"These are complementary outcomes: 100% − 80% = 20%."),q("For a fair six-sided die, what is the probability of rolling above 4?",["1/6","1/2","2/3","1/3"],3,"The favorable outcomes are 5 and 6: 2 out of 6 = 1/3.")],
  },
  {
    id:"independence",week:2,title:"A streak does not make you “due”",subtitle:"Understand independent events",concept:"Independent events do not change each other’s probability. A fair coin does not remember previous flips. For independent events, multiply probabilities to find the chance both happen.",rules:["Previous independent outcomes do not make a reversal due.","P(A and B) = P(A) × P(B) when A and B are independent.","Check independence first: real-world events often share causes."],example:{label:"THE COIN EXAMPLE",text:"Two independent fair flips have a 1/2 × 1/2 = 1/4 (25%) chance of both landing heads."},mission:"Catch one ‘we’re due for a win’ claim. Ask whether the events are actually independent.",questions:[q("A fair coin lands heads five times. What is the chance the next independent flip is tails?",["90%","50%","10%","100%"],1,"A fair, independent flip stays 50/50, regardless of its history."),q("Two independent devices each have a 10% chance of failing today. What is the chance both fail?",["20%","10%","1%","0.1%"],2,"Multiply the independent probabilities: 0.10 × 0.10 = 0.01 = 1%."),q("Which pair is most likely to share a cause and therefore need an independence check?",["Two separate fair coin flips","Two fair dice rolled separately","Rain and traffic delays in the same city","Two independent lottery draws"],2,"Rain can affect traffic, so treating those events as independent is risky.")],
  },
  {
    id:"expected-value",week:2,title:"What is a chance actually worth?",subtitle:"Find the long-run average outcome",concept:"Expected value is the probability-weighted average of possible outcomes. It can compare repeated choices, but it is not a guaranteed result on any one try.",rules:["Multiply each outcome by its probability, then add.","Account for costs when calculating expected net value.","Expected value alone does not capture risk or what you can afford to lose."],example:{label:"THE RAFFLE EXAMPLE",text:"A free raffle gives a 10% chance of $20 and 90% chance of $0. Its expected payout is 0.10 × $20 + 0.90 × $0 = $2."},mission:"Invent a two-outcome game. Calculate its expected payout, then subtract the entry cost.",questions:[q("A free game gives a 25% chance of $12 and otherwise $0. What is its expected payout?",["$12","$6","$3","$0.25"],2,"0.25 × $12 + 0.75 × $0 = $3."),q("A game has a $3 expected payout but costs $4 to enter. What is its expected net value?",["$7","−$1","$1","$3"],1,"Expected net value = expected payout − cost = $3 − $4 = −$1."),q("A game has an expected payout of $5. This means…",["You receive exactly $5 every time","You cannot lose","The probability-weighted average payout is $5","Half the outcomes pay $5"],2,"Expected value is an average across outcomes, not a promise about a single play.")],
  },
  {
    id:"percent-change",week:3,title:"Percent of what, exactly?",subtitle:"Decode discounts and financial headlines",concept:"A percentage change compares the change to the starting value. Percentage points simply subtract two percentages. Keeping the baseline in view prevents misleading comparisons.",rules:["Percentage change = (new − old) ÷ old × 100%.","A move from 10% to 15% is +5 percentage points, or a 50% relative increase.","Equal up and down percentages do not cancel: their baselines differ."],example:{label:"THE PRICE EXAMPLE",text:"A price rises from $40 to $50. That is a $10 increase on a $40 starting value: 10 ÷ 40 = 25%."},mission:"Find a percentage in a headline or promotion and identify the starting value.",questions:[q("A subscription rises from $20 to $25. What is the percentage increase?",["5%","20%","25%","125%"],2,"The $5 increase is divided by the original $20: 5 ÷ 20 = 25%."),q("A rate rises from 4% to 6%. How many percentage points is that?",["2","50","6","1.5"],0,"Subtract the rates: 6% − 4% = 2 percentage points. The relative increase is 50%."),q("$100 increases by 10%, then decreases by 10%. What remains?",["$100","$99","$90","$101"],1,"$100 × 1.10 = $110, then $110 × 0.90 = $99. The second change has a new baseline.")],
  },
  {
    id:"compounding",week:3,title:"Growth builds on growth",subtitle:"Understand simple compounding",concept:"Compounding applies a rate to an amount that already includes earlier growth. These examples use fixed hypothetical rates to make the arithmetic clear.",rules:["For a fixed rate, future value = starting value × (1 + rate)^periods.","Use a rate and a period that match: annual rates with years.","Fees, inflation, and changing returns affect real outcomes."],example:{label:"THE SAVINGS EXAMPLE",text:"At a hypothetical 10% per year, $100 becomes $110 after year one and $121 after year two: $110 × 1.10."},mission:"Compare two years of simple and compound growth on $100 at a hypothetical 5% annual rate.",questions:[q("$200 grows by a hypothetical 10% annually for two years. What is the final amount?",["$220","$240","$242","$400"],2,"$200 × 1.10 × 1.10 = $242."),q("Why does compound growth exceed simple growth at a positive fixed rate over multiple periods?",["The rate must double","Earlier growth also earns growth","There are no fees","The starting amount changes before growth"],1,"Compounding applies growth to both the starting amount and earlier growth."),q("$1,000 grows by 5% in one year. Ignoring fees, what is the ending balance?",["$1,500","$1,005","$1,050","$950"],2,"5% of $1,000 is $50, so the final balance is $1,050.")],
  },
  {
    id:"weighted-average",week:3,title:"Some numbers carry more weight",subtitle:"Compare baskets, budgets, and risk",concept:"A weighted mean accounts for different group sizes or shares. A category holding most of your budget should have more influence than a tiny category.",rules:["Multiply each value by its weight, then add.","Weights expressed as proportions should add to 1.","An average return does not reveal volatility or guarantee future results."],example:{label:"THE BASKET EXAMPLE",text:"If 80% of a hypothetical basket grows 5% and 20% grows 2%, the weighted growth is 0.80 × 5% + 0.20 × 2% = 4.4%."},mission:"Split a sample $100 budget into two categories and calculate a weighted price increase.",questions:[q("Half a hypothetical basket returns 4% and half returns 8%. What is the weighted return?",["12%","4%","6%","8%"],2,"0.5 × 4% + 0.5 × 8% = 6%."),q("80% of a basket grows 5% and 20% grows 2%. What is its weighted growth?",["3.5%","7%","4.4%","5%"],2,"0.80 × 5% + 0.20 × 2% = 4% + 0.4% = 4.4%."),q("Two hypothetical investments have the same average return. Which fact is still useful for comparing their risk?",["Only their names","Their return variability","The same average again","Their display order"],1,"The same average can hide very different swings. Variation is one useful risk measure.")],
  },
  {
    id:"sampling",week:4,title:"Who did we actually ask?",subtitle:"Spot biased samples",concept:"A sample is a subset used to learn about a larger population. Who is included matters as much as how many people answer: a huge biased sample can still mislead.",rules:["Define the population you want to understand.","Random sampling can reduce selection bias; voluntary responses may overrepresent strong opinions.","Larger well-designed samples reduce random sampling error, but size alone does not fix bias."],example:{label:"THE GYM EXAMPLE",text:"Asking only gym members how often the whole town exercises will likely overestimate activity, even if thousands respond."},mission:"Find a survey result. Identify the population, sample, and one group that might be missing.",questions:[q("To estimate a town’s exercise habits, which sample is most likely to be biased?",["Randomly selected residents","Only members at a local gym","A random sample across neighborhoods","Randomly selected households"],1,"Gym members are selected for an interest in exercise and may not represent the town."),q("Does increasing a biased sample from 100 to 10,000 automatically remove selection bias?",["Yes, always","Only if responses are fast","No","Only for percentages"],2,"A bigger sample of the wrong group can still systematically miss the target population."),q("In a town-wide survey, the population of interest is…",["Only the respondents","Only people who agree","Everyone in the town the survey aims to describe","The survey questions"],2,"The population is the full group you want to understand; respondents are the sample.")],
  },
  {
    id:"correlation",week:4,title:"Together does not mean because",subtitle:"Separate association from causation",concept:"Correlation means two things vary together. It does not prove that one causes the other. A third factor, reverse causation, or coincidence can explain the relationship.",rules:["Look for a possible common cause, called a confounder.","Ask whether the direction of causation could be reversed.","Well-designed randomized experiments support stronger causal conclusions than simple correlations."],example:{label:"THE SUMMER EXAMPLE",text:"Ice cream sales and swimming activity both rise in warm weather. That does not show that ice cream causes people to swim: temperature influences both."},mission:"Find a ‘people who do X have more Y’ claim and suggest one possible confounder.",questions:[q("Ice cream sales and swimming both rise in summer. A likely shared cause is…",["The price of cones","Warm weather","Swimming causes all ice cream sales","Random assignment"],1,"Warm weather can increase both activities without one causing the other."),q("An app finds frequent users have higher productivity. Can this alone prove the app caused it?",["Yes","Only if the chart is clear","No, other explanations remain","Yes, if the sample is large"],2,"Already productive people might use the app more, or a third factor could explain both."),q("Which design better supports testing whether a new study method improves scores?",["Compare volunteers to everyone else","Ask only top students","Randomly assign students to methods and compare","Count social media likes"],2,"Random assignment helps balance confounders so differences are more plausibly due to the method.")],
  },
  {
    id:"evidence",week:4,title:"Make a decision without false certainty",subtitle:"Base rates, small samples, and practical impact",concept:"Good decisions combine the background rate, the size of an effect, and uncertainty. A dramatic relative change can still be a small absolute change.",rules:["Always ask for the denominator: ‘out of how many?’", "Check absolute and relative changes before judging importance.", "Small experiments can be noisy; more representative evidence can change your conclusion."],example:{label:"THE FAILURE-RATE EXAMPLE",text:"If failures fall from 2 in 1,000 to 1 in 1,000, that is a 50% relative reduction but only a 0.1 percentage-point absolute reduction."},mission:"Take one real-world claim and ask: compared with what, out of how many, and how certain?",questions:[q("A failure rate falls from 2 in 1,000 to 1 in 1,000. What is the relative reduction?",["0.1%","1%","50%","100%"],2,"Failures fall by 1 from an original 2: 1 ÷ 2 = 50%."),q("That same rate falls from 0.2% to 0.1%. What is the absolute reduction in percentage points?",["50","0.1","1","0.5"],1,"Subtract the percentages: 0.2% − 0.1% = 0.1 percentage points."),q("A new checkout gets 3 purchases from 5 visitors, versus 2 from 5 for the old one. What is the most careful conclusion?",["The new checkout will always win","The old checkout is useless","The sample is tiny; collect more comparable data","Three purchases proves causation"],2,"A one-purchase gap in such small samples is noisy. More well-designed observations help assess the difference.")],
  },
];
